package freenet.clients.http.uielements;

public enum HTMLClass {

	ADVANCED("advanced"),
	ALERTSLINE("alerts-line"),
	BOOKMARKSBOX("bookmarks-box"),
	CAT("cat"),
	CONFIG("config"),
	CONFIGPREFIX("configprefix"),
	CONTAINSALERT("contains-alert"),
	CONTAINSINFORMATION("contains-information"),
	CONTAINSWARNING("contains-warning"),
	DARKNETDIV("darknetDiv"),
	HIDDEN("hidden"),
	HISTOGRAMLABEL("histogramLabel"),
	HISTOGRAMDISCONNECTED("histogramDisconnected"),
	HISTOGRAMCONNECTED("histogramConnected"),
	INFOBOX("infobox"),
	INFOBOXALERT("infobox-alert"),
	INFOBOXCONTENT("infobox-content"),
	INFOBOXERROR("infobox-error"),
	INFOBOXHEADER("infobox-header"),
	INFOBOXINFORMATION("infobox-information"),
	INFOBOXMINOR("infobox-minor"),
	INFOBOXNORMAL("infobox-normal"),
	INFOBOXQUERY("infobox-query"),
	INFOBOXSUCCESS("infobox-success"),
	INFOBOXWARNING("infobox-warning"),
	ITEM("item"),
	NAVLISTSELECTED("navlist-selected"),
	NAVLISTNOTSELECTED("navlist-not-selected"),
	N2NTMMESSAGETEXT("n2ntm-message-text"),
	NONE("none"),
	NULL(""),
	NOWRAP("NOWRAP"),
	OPENNETDIV("opennetDiv"),
	PEERCIRCLE("peercircle"),
	PEERSAVERAGE("avg-peers"),
	PEERSFEW("few-peers"),
	PEERSFULL("full-peers"),
	PEERSVERYFEW("very-few-peers"),
	PLUGIN("plugin"),
	PLUGINGROUP("plugin-group"),
	PLUGINGROUPTITLE("plugin-group-title"),
	PROGRESSBAR("progressbar"),
	PROGRESSBARDONE("progressbar-done"),
	PROGRESSBARFAILED("progressbar-failed"),
	PROGRESSBARFAILED2("progressbar-failed2"),
	PROGRESSBARFINAL("progress_fraction_finalized"),
	PROGRESSBARMIN("progressbar-min"),
	PROGRESSBARNOTFINAL("progress_fraction_not_finalized"),
	PROGRESSBARPEERS("progressbar-peers"),
	REQUESTDELETE("request-delete"),
	REQUESTDELETEFINISHEDDOWNLOADS("request-delete-finished-downloads"),
	REQUESTPRIORITY("request-priority"),
	REQUESTRECOMMEND("request-recommend"),
	REQUESTTABLEFORM("request-table-form"),
	ROOT("root"),
	SEPERATOR("separator"),
	SIMPLE("simple"),
	SUBMENUSELECTED("submenuitem-selected"),
	SUBMENUNOTSELECTED("submenuitem-not-selected"),
	SUBNAVLIST("subnavlist"),
	SUBNAVLISTSELECTED("subnavlist-selected"),
	TOGGLEABLE("toggleable"),
	TRANSLATION("translation"),
	WARNING("warning");

	public final String name;

	private HTMLClass(String CLASSNAME) {
		this.name = CLASSNAME;
	}
}
