package freenet.clients.http.uielements;

public enum Identifier {
	ACCESSDENIED("access-denied"),
	BOOKMARKS("bookmarks"),
	BOOKMARKADDCONFIRM("add-bookmark-confirm"),
	BOOKMARKEDIT("bookmarkedit"),
	CHATLIST("chat-list"),
	CONTENT("content"),
	CONFIGURATIONAPPLIED("configuration-applied"),
	CONFIGURATIONERROR("configuration-error"),
	CONFIRMDELETETITLE("confirm-delete-title"),
	CONFIRMEXTERNALLINK("confirm-external-link"),
	COMPLETEDDOWNLOADTODISK("completedDownloadToDisk"),
	COMPLETEDDOWNLOADTOTEMP("completedDownloadToTemp"),
	COMPLETEDDIRUPLOAD("completedDirUpload"),
	COMPLETEDUPLOAD("completedUpload"),
	CONNECTIVITYSUMMARY("connectivity-summary"),
	DARKNETEXPLAINATIONS("darknet-explanations"),
	DARKNETREMOVENODE("darknet-remove-node"),
	FAILEDDIRUPLOAD("failedDirUpload"),
	FAILEDDOWNLOAD("failedDownload"),
	FAILEDUPLOAD("failedUpload"),
	FETCHKEY("fetch-key"),
	FREENETDESCRIPTION("freenet-description"),
	FREESITEINSERT("freesite-insert"),
	GROUPEDDOWNLOAD("grouped-downloads"),
	IEWARNING("internet-explorer-used"),
	INSERTQUEUE("insert-queue"),
	JAVASCRIPTTEST("javascript-test"),
	PAGE("page"),
	PERSISTENCEFIELDS("persistenceFields"),
	MESSAGESUMMARYBOX("messages-summary-box"),
	NAVBAR("navbar"),
	NAVLIST("navlist"),
	N2NBOX("n2nbox"),
	NODEADDED("node-added"),
	PANICBUTTON("panic-button"),
	PANICCONFIRM("confirm-panic"),
	PASSWORDCHANGE("password-change"),
	PASSWORDERROR("password-error"),
	QUEUEEMPTY("queue-empty"),
	QUEUELEGEND("queue-legend"),
	PLUGINRELOAD("plugin-reload"),
	RECOMMENDFILE("recommend-file"),
	RESETCONFIRM("reset-confirm"),
	RESTARTCONFIRM("restart-confirm"),
	SEARCH("search-freenet"),
	SELECTEDSUBNAVBAR("selected-subnavbar"),
	SELECTEDSUBNAVBARLIST("selected-subnavbar-list"),
	SHUTDOWNCONFIRM("shutdown-confirm"),
	SHUTDOWNPROGRESSING("shutdown-progressing"),
	STARTPROGRESS("start-progress"),
	STATUSBAR("statusbar"),
	STATUSBARALERTS("statusbar-alerts"),
	STATUSBARCONTAINER("statusbar-container"),
	STATUSBARLANGUAGE("statusbar-language"),
	STATUSBARSECLEVELS("statusbar-seclevels"),
	STATUSBARSWITCHMODE("statusbar-switchmode"),
	STATISTICSGENERATING("statistics-generating"),
	THREADDUMPGENERATION("thread-dump-generation"),
	TOPBAR("topbar"),
	TRANSLATIONOVERRIDE("translation-override"),
	UNCOMPLETEDDIRUPLOAD("uncompletedDirUpload"),
	UNCOMPLETEDDOWNLOAD("uncompletedDownload"),
	UNCOMPLETEDUPLOAD("uncompletedUpload"),
	UPDATENODECONFIRM("update-node-confirm"),
	VERSION("freenet-version"),
	WRONGPASSWORD("wrong-password");

	public final String name;

	private Identifier(String id) {
		this.name = id;
	}
}
